import { v } from 'convex/values';
import { query, mutation } from './_generated/server';
function authorize(secret:string) { if(!process.env.CONVEX_BACKEND_SECRET || process.env.CONVEX_BACKEND_SECRET!==secret) throw new Error('UNAUTHORIZED_BACKEND'); }
export const token = query({args:{secret:v.string(),professorEmail:v.string()},handler:async(ctx,args)=>{authorize(args.secret); return ctx.db.query('calendarTokens').withIndex('by_professor',q=>q.eq('professorEmail',args.professorEmail)).unique();}});
export const saveToken = mutation({args:{secret:v.string(),professorEmail:v.string(),encrypted:v.string()},handler:async(ctx,args)=>{authorize(args.secret);const existing=await ctx.db.query('calendarTokens').withIndex('by_professor',q=>q.eq('professorEmail',args.professorEmail)).unique();if(existing) await ctx.db.patch(existing._id,{encrypted:args.encrypted});else await ctx.db.insert('calendarTokens',{professorEmail:args.professorEmail,encrypted:args.encrypted});}});
export const bookings = query({args:{secret:v.string(),professorEmail:v.string()},handler:async(ctx,args)=>{authorize(args.secret);return (await ctx.db.query('bookings').withIndex('by_professor',q=>q.eq('professorEmail',args.professorEmail)).collect()).filter(b=>b.status==='pending'||b.status==='confirmed');}});
export const reserve = mutation({args:{secret:v.string(),professorEmail:v.string(),studentId:v.id('students'),subjectId:v.id('subjects'),start:v.string(),end:v.string()},handler:async(ctx,args)=>{
 authorize(args.secret);const student=await ctx.db.get(args.studentId);const subject=await ctx.db.get(args.subjectId);const teacher=subject?await ctx.db.get(subject.teacherId):null;
 if(!student||!subject||student.teacherId!==subject.teacherId||teacher?.email!==args.professorEmail)throw new Error('FORBIDDEN');
 const all=await ctx.db.query('bookings').withIndex('by_professor',q=>q.eq('professorEmail',args.professorEmail)).collect();
 if(all.some(b=>(b.status==='pending'||b.status==='confirmed')&&b.start<args.end&&b.end>args.start))throw new Error('SLOT_UNAVAILABLE');
 return ctx.db.insert('bookings',{professorEmail:args.professorEmail,studentId:args.studentId,subjectId:args.subjectId,start:args.start,end:args.end,status:'pending'});
}});
export const finishBooking = mutation({args:{secret:v.string(),id:v.id('bookings'),status:v.string(),googleEventId:v.optional(v.string())},handler:async(ctx,args)=>{authorize(args.secret);await ctx.db.patch(args.id,{status:args.status,...(args.googleEventId?{googleEventId:args.googleEventId}:{})});}});
export const claimNotification = mutation({args:{secret:v.string(),professorEmail:v.string(),studentId:v.id('students'),subjectId:v.id('subjects'),key:v.string(),provider:v.string()},handler:async(ctx,args)=>{authorize(args.secret);const existing=await ctx.db.query('notificationEvents').withIndex('by_key',q=>q.eq('key',args.key)).unique();if(existing)return null;const {secret,...record}=args;return ctx.db.insert('notificationEvents',{...record,status:'pending'});}});
export const finishNotification = mutation({args:{secret:v.string(),id:v.id('notificationEvents'),status:v.string()},handler:async(ctx,args)=>{authorize(args.secret);await ctx.db.patch(args.id,{status:args.status,...(args.status==='dispatched'?{sentAt:Date.now()}:{})});}});
export const riskTargets = query({args:{secret:v.string(),professorEmail:v.string(),subjectId:v.optional(v.id('subjects'))},handler:async(ctx,args)=>{
 authorize(args.secret);const teacher=await ctx.db.query('teachers').withIndex('by_email',q=>q.eq('email',args.professorEmail)).unique();if(!teacher)return [];
 const subjects=(await ctx.db.query('subjects').withIndex('by_teacher',q=>q.eq('teacherId',teacher._id)).collect()).filter(s=>!args.subjectId||s._id===args.subjectId);
 const students=await ctx.db.query('students').withIndex('by_teacher',q=>q.eq('teacherId',teacher._id)).collect();const targets=[];
 for(const subject of subjects){const attendance=await ctx.db.query('attendanceRecords').withIndex('by_subject',q=>q.eq('subjectId',subject._id)).collect();const marks=await ctx.db.query('marksRecords').withIndex('by_subject',q=>q.eq('subjectId',subject._id)).collect();const assessments=await ctx.db.query('assessments').withIndex('by_subject',q=>q.eq('subjectId',subject._id)).collect();
 for(const student of students.filter(s=>s.active)){const records=attendance.filter(a=>a.studentId===student._id);const present=records.filter(a=>a.status==='P').length;const total=records.length;const percentage=total?present/total*100:null;const sorted=marks.filter(m=>m.studentId===student._id).sort((a,b)=>(assessments.find(t=>t._id===b.assessmentId)?.assessmentDate??'').localeCompare(assessments.find(t=>t._id===a.assessmentId)?.assessmentDate??''));const latest=sorted[0]?.percentage??null;const previous=sorted[1]?.percentage??null;const marksRisk=latest!==null&&(latest<subject.marksThreshold||(previous!==null&&previous-latest>=10));
 if((percentage!==null&&percentage<subject.attendanceThreshold)||marksRisk)targets.push({studentId:student._id,subjectId:subject._id,name:student.name,email:student.email,phone:student.phone,subjectName:subject.name,present,total,attendancePercentage:percentage,threshold:subject.attendanceThreshold,classesToRecover:total?Math.max(0,Math.ceil((subject.attendanceThreshold*total-100*present)/(100-subject.attendanceThreshold))):0,latestScore:latest,previousScore:previous,marksRisk});
 }}return targets;
}});
